apiVersion: rd.kanzhun.com/v1beta1
kind: RedisCluster
metadata:
  name: rediscluster-sample
spec:
  # Add fields here
  size: 2
  image: harbor.weizhipin.com/cloud-native/redis:5.0.0-alpine
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005  
  
